on:
  workflow_call:
    inputs:
      tag:
        description: 'Tag for docker image'
        required: true
        type: string
      ecr_push_role_arn:
        description: 'IAM role ARN for ECR push via OIDC'
        required: true
        type: string
    secrets:
      SNYK_OPG_ORG_TOKEN:
        required: true

permissions:
  id-token: write
  contents: read
  security-events: write

defaults:
  run:
    shell: bash

jobs:
  docker_build_scan_push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: service-maintenance
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
        with:
          persist-credentials: false
      - name: Build Image
        id: build_image
        run: |
          docker build -t maintenance-app .
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          role-to-assume: ${{ inputs.ecr_push_role_arn }}
          aws-region: eu-west-1
          role-duration-seconds: 900
          role-session-name: OPGMaintenanceECRGithubAction
      - name: ECR Login
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@03f1aad4c6c7ffd436567f42f9384779290529bd # v2.1.7
        with:
          registries: 311462405659
      - name: Snyk Scan
        uses: ministryofjustice/opg-github-actions/actions/snyk-scan@722a5f955424aaba01e9ca43d68390cd4048d6e1 # v4.10.2
        with:
          SNYK_TEST_IMAGE: maintenance-app:latest
          SNYK_TOKEN: ${{ secrets.SNYK_OPG_ORG_TOKEN }}
          snyk_test_args: >
            --severity-threshold=high
      - name: Upload Snyk scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@db488ddef3bf6cb639b32c2e9a7c0a7ea8271d28 # v4.37.8
        if: always()
        with:
          sarif_file: "test-results/snyk.sarif"
      - name: Push Container
        env:
          ECR_REGISTRY: ${{ steps.login_ecr.outputs.registry }}
          MAINTENANCE_ECR_REPOSITORY: maintenance/maintenance_app
          TAG: ${{ inputs.tag }}
        run: |
          docker tag maintenance-app:latest $ECR_REGISTRY/$MAINTENANCE_ECR_REPOSITORY:${TAG}
          if [ ${GITHUB_REF} == 'refs/heads/main' ]; then
            docker tag maintenance-app:latest $ECR_REGISTRY/$MAINTENANCE_ECR_REPOSITORY:main-${TAG}
            docker tag maintenance-app:latest $ECR_REGISTRY/$MAINTENANCE_ECR_REPOSITORY:latest
          fi
            docker push --all-tags $ECR_REGISTRY/$MAINTENANCE_ECR_REPOSITORY
