on:
  workflow_call:
    inputs:
      tag:
        description: 'Tag for docker image'
        required: true
        type: string
      ecr_push_role_arn:
        description: 'IAM role ARN for ECR push via OIDC'
        required: true
        type: string
    secrets:
      SNYK_OPG_ORG_TOKEN:
        required: true

permissions:
  id-token: write
  contents: read
  security-events: write

defaults:
  run:
    shell: bash

jobs:
  docker_build_scan_push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: service-maintenance
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Extract branch name
        id: extract_branch
        run: |
          if [ "$GITHUB_EVENT_NAME" == "push" ]; then
            echo BRANCH_NAME=main >> $GITHUB_ENV
          else
            echo BRANCH_NAME=${{ github.head_ref }} >> $GITHUB_ENV
          fi
      - name: Build Image
        id: build_image
        run: |
          docker build -t maintenance-app .
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # v1.7.0
        with:
          role-to-assume: ${{ inputs.ecr_push_role_arn }}
          aws-region: eu-west-1
          role-duration-seconds: 900
          role-session-name: OPGMaintenanceECRGithubAction
      - name: ECR Login
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@5a88a04c91d5c6f97aae0d9be790e64d9b1d47b7 # v1.7.1
        with:
          registries: 311462405659
      - name: Snyk Scan
        uses: ministryofjustice/opg-github-actions/actions/snyk-scan@939ca6ddfc2bafefa48b0730ea0268bd75a25876 # v4.9.1
        with:
          SNYK_TEST_IMAGE: maintenance-app:latest
          SNYK_TOKEN: ${{ secrets.SNYK_OPG_ORG_TOKEN }}
          snyk_test_args: >
            --severity-threshold=high
      - name: Upload Snyk scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@99df26d4f13ea111d4ec1a7dddef6063f76b97e9 # v4.37.0
        if: always()
        with:
          sarif_file: "test-results/snyk.sarif"
      - name: Push Container
        env:
          ECR_REGISTRY: ${{ steps.login_ecr.outputs.registry }}
          MAINTENANCE_ECR_REPOSITORY: maintenance/maintenance_app
        run: |
          docker tag maintenance-app:latest $ECR_REGISTRY/$MAINTENANCE_ECR_REPOSITORY:${{ inputs.tag }}
          if [ $BRANCH_NAME == "main" ]; then
            docker tag maintenance-app:latest $ECR_REGISTRY/$MAINTENANCE_ECR_REPOSITORY:main-${{ inputs.tag }}
            docker tag maintenance-app:latest $ECR_REGISTRY/$MAINTENANCE_ECR_REPOSITORY:latest
          fi
            docker push --all-tags $ECR_REGISTRY/$MAINTENANCE_ECR_REPOSITORY
