on:
  workflow_call:
    inputs:
      workspace_name:
        description: 'The terraform workspace to target for environment cleanup actions'
        required: true
        type: string

jobs:
  github_environment_cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: use github cli to get environment details (not env vars)
        run: |
          gh api \
          -H "Accept: application/vnd.github+json" \
          /repos/ministryofjustice/opg-maintenance/environments/maintenance_dev_37uml2507
          echo "maintenance_dev_${{ inputs.workspace_name }}"
