on:
  workflow_call:
    inputs:
      workspace_name:
        description: 'The terraform workspace to target for environment cleanup actions'
        required: true
        type: string

jobs:
  github_environment_cleanup:
    permissions:
      deployments: write
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.OPG_MAINTENANCE_GITHUB_ENVIRONMENT_DELETION_DEPLOY_KEY_SSH_PRIVATE_KEY }}
      - name: use github cli to get environment details (not env vars)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
          -H "Accept: application/vnd.github+json" \
          /repos/ministryofjustice/opg-maintenance/environments/36lpal871

          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            /repos/ministryofjustice/opg-maintenance/environments/36lpal871

          echo "maintenance_dev_${{ inputs.workspace_name }}"
