name: "[Workflow] Path To Live"

on:
  push:
    branches:
      - main

permissions:
  contents: write
  security-events: write
  pull-requests: read
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  go_build_test:
    name: Go Build and Test App
    uses: ./.github/workflows/go_job.yml

  workflow_variables:
    name: Output workflow variables
    runs-on: ubuntu-latest
    outputs:
      semver_tag: ${{ steps.semver_tag.outputs.tag }}
      environment_terraform_version: ${{ steps.terraform_version_environment.outputs.version }}
      account_terraform_version: ${{ steps.terraform_version_account.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false
      - name: Set terraform version - environment
        id: terraform_version_environment
        uses: ministryofjustice/opg-github-actions/actions/terraform-version@ceeda9d30ec7f6705c819d0b7664b9a79df99a3b # v4.8.0
        with:
          terraform_directory: "./terraform/environment"
      - name: Set terraform version - account
        id: terraform_version_account
        uses: ministryofjustice/opg-github-actions/actions/terraform-version@ceeda9d30ec7f6705c819d0b7664b9a79df99a3b # v4.8.0
        with:
          terraform_directory: "./terraform/account"
      - name: Bump version and push tag
        uses: ministryofjustice/opg-github-actions/actions/semver@ceeda9d30ec7f6705c819d0b7664b9a79df99a3b # v4.8.0
        id: semver_tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          create_release: true
          default_bump: minor

  docker_build_scan_push:
    name: Docker Build, Scan and Push
    uses: ./.github/workflows/docker_job.yml
    needs: [go_build_test,workflow_variables]
    with:
      tag: ${{ needs.workflow_variables.outputs.semver_tag }}
      ecr_push_role_arn: arn:aws:iam::311462405659:role/opg-maintenance-github-actions-ecr-push
    secrets: inherit

  terraform_account_workflow_development:
    name: TF Development - Account
    uses: ministryofjustice/opg-github-workflows/.github/workflows/build-infrastructure-terraform-oidc.yml@f567efb2782f73a972073276a00bc4bcf92a3728 # v3.19.2
    needs:
      - workflow_variables
    with:
      terraform_version: ${{ needs.workflow_variables.outputs.account_terraform_version }}
      terraform_workspace: development
      is_ephemeral: false
      terraform_apply: true
      terraform_directory: ./terraform/account
      oidc_role_to_assume: arn:aws:iam::631181914621:role/oidc-opg-maintenance-development

  terraform_account_workflow_production:
    name: TF Production - Account
    uses: ministryofjustice/opg-github-workflows/.github/workflows/build-infrastructure-terraform-oidc.yml@f567efb2782f73a972073276a00bc4bcf92a3728 # v3.19.2
    needs:
      - workflow_variables
      - terraform_account_workflow_development
    with:
      terraform_version: ${{ needs.workflow_variables.outputs.account_terraform_version }}
      terraform_workspace: production
      is_ephemeral: false
      terraform_apply: true
      terraform_directory: ./terraform/account
      oidc_role_to_assume: arn:aws:iam::631181914621:role/oidc-opg-maintenance-production

  production_deploy:
    name: Production Environment Deploy
    uses: ministryofjustice/opg-github-workflows/.github/workflows/build-infrastructure-terraform-oidc.yml@f567efb2782f73a972073276a00bc4bcf92a3728 # v3.19.2
    needs: [docker_build_scan_push, workflow_variables, terraform_account_workflow_production]
    with:
      terraform_version: ${{ needs.workflow_variables.outputs.environment_terraform_version }}
      use_ssh_private_key: true
      terraform_workspace: production
      is_ephemeral: false
      terraform_apply: true
      terraform_directory: ./terraform/environment
      terraform_variables: "-var container_version=${{ needs.workflow_variables.outputs.semver_tag }}"
      persist_artifacts: false
      oidc_role_to_assume: arn:aws:iam::631181914621:role/oidc-opg-maintenance-production
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY }}

  end_of_main_workflow:
    name: End of Main Workflow
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: maintenance_production
    needs: [production_deploy]
    steps:
      - name: End of PR Workflow
        run: |
          echo "production environment tested, built and deployed"
