on:
  workflow_call:
    inputs:
      pre_release:
        description: "Whether tag is prerelease or not"
        default: true
        type: boolean
    outputs:
      version_tag:
        description: "Docker Image Tag"
        value: ${{ jobs.create_tags.outputs.docker_tag }}
      environment_workspace_name:
        description: "Terraform Environment Workspace Name"
        value: ${{ jobs.generate_environment_workspace_name.outputs.environment_workspace_name }}

jobs:
  create_tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Extract branch name
        id: extract_branch
        run: |
          if [ "$GITHUB_EVENT_NAME" == "push" ]; then
            echo BRANCH_NAME=main >> $GITHUB_ENV
          else
            branch=${{ github.head_ref }}
            branch=${branch//-}
            branch=${branch//_}
            branch=${branch//\/}
            echo BRANCH_NAME=${branch} >> $GITHUB_ENV
          fi
      - name: generate semver tag and release
        id: semver_tag
        uses: ministryofjustice/opg-github-actions/actions/semver@b8868247a908f74fafe1905701391580575a6d35 # v4.3.10
        with:
          prerelease: ${{ inputs.pre_release }}
          default_bump: minor
    outputs:
      docker_tag: ${{ steps.semver_tag.outputs.tag }}

  generate_environment_workspace_name:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Generate workspace name
        id: name_workspace
        run: |
          workspace=${{ github.event.number }}${{ github.head_ref }}
          workspace=${workspace//-}
          workspace=${workspace//_}
          workspace=${workspace//\/}
          workspace=${workspace:0:11}
          workspace=$(echo ${workspace} | tr '[:upper:]' '[:lower:]')
          echo ::set-output name=name::${workspace}
          echo ${workspace}
    outputs:
      environment_workspace_name: ${{ steps.name_workspace.outputs.name }}
