on:
  workflow_call:

jobs:
  create_tags:
    name: Bump Tag Version
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        id: extract_branch
        run: |
          if [ "$GITHUB_EVENT_NAME" == "push" ]; then
            echo BRANCH_NAME=main >> $GITHUB_ENV
          else
            echo BRANCH_NAME=${{ github.head_ref }} >> $GITHUB_ENV
          fi
      - name: Bump version
        id: bump_version
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: 0.0.0
          DEFAULT_BUMP: minor
          PRERELEASE_SUFFIX: ${{ env.BRANCH_NAME }}
          RELEASE_BRANCHES: main
          WITH_V: true
    outputs:
      version_tag: ${{steps.bump_version.outputs.tag}}

  generate_environment_workspace_name:
    name: Generate Environment Workspace Name
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Print output from previous a job
        id: name_workspace
        run: |
          echo ::set-output name=name::$(echo ${{ github.event.number }}${{ github.head_ref }} | tr '[:upper:]' '[:lower:]')
    outputs:
      environment_workspace_name: ${{steps.name_workspace.outputs.name}}
